apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.10.4
    helm.sh/chart: argo-cd-6.7.3
data:
  admin.enabled: "true"
  application.instanceLabelKey: argocd.argoproj.io/instance
  exec.enabled: "false"
  server.rbac.log.enforce.enable: "false"
  timeout.hard.reconciliation: 0s
  timeout.reconciliation: 180s
  notifications: |
    triggers:
      - name: on-rollback
        when: app.status.operation.completed
        condition: app.operation.sync.result.reason == 'rollback'
        template: rollback-notification
    templates:
      - name: rollback-notification
        webhook:
          url: "https://apis.elven.works/external/v2/delivery/ea9763ba-74ef-468a-9cb2-5c3400a5696e?token=CUQwqqg3eVmQyjHXmihUILrKgT7rYSwS"
          method: POST
          body: |
            --header 'Content-Type: application/json' \
            --header 'User-Agent: 1PwebhookDeliveries/1.0' \
            --data '{
              "organization": "461b4831-1728-4b8c-8983-c7baccc2a544",
              "description": "< Description >",
              "version": "< Version >",
              "type": "rollback"
            }'
