apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argo-cd
data:
  notifications: |
    triggers:
      - name: on-rollback
        when: app.status.operationState.phase in ['Succeeded']
        template: rollback-notification
          
      # - name: on-rollback
      #   when: app.status.operation.completed
      #   condition: app.operation.sync.result.reason == 'rollback'
      #   template: rollback-notification
    template.rollback-notification:
      - webhook:
          url: "https://apis.elven.works/external/v2/delivery/ea9763ba-74ef-468a-9cb2-5c3400a5696e?token=CUQwqqg3eVmQyjHXmihUILrKgT7rYSwS"
          method: POST
          body: |
            {
              "organization": "461b4831-1728-4b8c-8983-c7baccc2a544",
              "description": "Rollback",
              "version": "{{.app.spec.source.targetRevision}}",
              "type": "rollback"
            }
          headers:
            - name: Content-Type
              value: application/json
            - name: User-Agent
              value: 1PwebhookDeliveries/1.0
