apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appargoteste
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-rollbackt.rollbackt: ""
spec:
  project: default
  source:
    repoURL: "https://github.com/pavanandersen/testeArgoCD"
    targetRevision: main
    path: k8s
  destination:+
    server: "https://kubernetes.default.svc"
    namespace: default