apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisdb
  namespace: testespace
spec:
  selector:
    matchLabels:
      app: redisdb
  template:
    metadata:
      labels:
        app: redisdb
    spec:
      containers:
      - name: redisdb
        image: redis:latest
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: testespace
spec:
  type: ClusterIP
  ports:
    - port: 6379
  selector:
    app: redisdb
