project: default
source:
  repoURL: 'https://github.com/pavanandersen/testeArgoCD.git'
  path: k8s/
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
syncPolicy:
  syncOptions:
    - CreateNamespace=true

