apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mario
  template:
    metadata:
      labels:
        app: mario
    spec:
      containers:
      - name: mario
        image: kaminskypavel/mario:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mario-service
spec:
  type: LoadBalancer  # Para acesso externo; use ClusterIP para acesso interno
  ports:
  - port: 4545
    targetPort: 8080
    protocol: TCP
  selector:
    app: mario