apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows95
spec:
  replicas: 1
  selector:
    matchLabels:
      app: win95
  template:
    metadata:
      labels:
        app: win95
    spec:
      containers:
      - name: win95
        image: toolboc/windows95:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: windows95-service
spec:
  type: LoadBalancer  # Para acesso externo; use ClusterIP para acesso interno
  ports:
  - port: 8000
    targetPort: 80
    protocol: TCP
  selector:
    app: win95