apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-segundo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxseg
  template:
    metadata:
      labels:
        app: nginxseg
    spec:
      containers:
      - name: nginxseg
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-serv-segundo
spec:
  type: LoadBalancer  # Para acesso externo; use ClusterIP para acesso interno
  ports:
  - port: 8383
    targetPort: 80
    protocol: TCP
  selector:
    app: nginxseg